[package]
authors = ["The Winch Project Developers"]
name = "winch-codegen"
description = "Winch code generation library"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
version = "0.1.0"
rust-version = "1.64.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.93", default-features = false }
seahorn-stubs = {path = "src/seahorn-stubs"}

[features]
x64 = []
arm64 = []
all-arch = ["x64", "arm64"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"
opt-level = "z"
# -Warithmetic-overflow -Coverflow-checks=yes -Cpanic=abort