[package]
authors = ["The Winch Project Developers"]
name = "winch-codegen"
description = "Winch code generation library"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
version = "0.1.0"
rust-version = "1.64.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.93", default-features = false }
seahorn-stubs = {path = "src/seahorn-stubs"}
libc-alloc = {path = "src/libc-alloc"}
smallvec = { version = "1.10.0", default-features = false }
no_std_io = "0.5"

[features]
x64 = []
arm64 = []
all-arch = ["x64", "arm64"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"
# opt-level = "z"
opt-level = 0
debug = 2
# -Warithmetic-overflow -Coverflow-checks=yes -Cpanic=abort

[[bin]]
name = "visit_cmp_ops"
path = "src/visit_cmp_ops.rs"

[[bin]]
name = "visit_setup"
path = "src/visit_setup.rs"

[[bin]]
name = "visit_arith"
path = "src/visit_arith.rs"

[[bin]]
name = "visit_funcs"
path = "src/visit_funcs.rs"
